image: guikar741/python-glucose:1.0

stages:
  - executar

executar:
  stage: executar
  script:
    - python trab.py > out.txt
  artifacts:
    name: SAIDA-SATSOLVER-$CI_PIPELINE_ID
    paths:
      - out.txt

