image: guikar741/python-glucose:1.5

stages:
  - executar

executar:
  stage: executar
  script:
    - python trab.py > saida.txt
  artifacts:
    name: SAIDA-SATSOLVER-$CI_PIPELINE_ID
    paths:
      - entrada.txt
      - saida.txt

